name: update-token

on:
  schedule:
    - cron: '5 0 * * *'  # Every day at 12:05am UTC
  workflow_dispatch:

jobs:
  fetch-and-save-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get token from NJ Transit
        run: |
          echo "Requesting token..."
          curl -v -X POST "https://raildata.njtransit.com/api/GTFSRT/getToken" \
          -H "accept: text/plain" \
          -F "username=${{ secrets.NJTRANSIT_USER }}" \
          -F "password=${{ secrets.NJTRANSIT_PASS }}"

      - name: Commit token file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add token.json
          git commit -m "Update token.json"
          git push
