name: update-token

on:
  schedule:
    - cron: '5 0 * * *'  # Every day at 12:05 AM
  workflow_dispatch:

jobs:
  fetch-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get token from NJ Transit
        run: |
          echo "Requesting token..."
          response=$(curl -s -X POST "https://raildata.njtransit.com/api/GTFSRT/getToken" \
            -H "accept: text/plain" \
            -F "username=${{ secrets.NJTRANSIT_USER }}" \
            -F "password=${{ secrets.NJTRANSIT_PASS }}")

          if [[ -z "$response" ]]; then
            echo "Failed to get token: empty response"
            exit 1
          fi

          echo "$response" > token.json
          echo "Token saved to token.json"

      - name: Commit token file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add token.json
          git commit -m "Update token.json"
          git push
